openapi: 3.0.0
info:
  version: 1.0.0
  title: Customer Profiling
  description: This API will be called after the user has successfully signed up and verified the email. This API creates the user profile with all necessary details about the user such name, GSTIN, PAN, mobile etc.
tags:
  - name: profile
paths:
  /v1/customer/profile:
    post:
      summary: creates customer profile with customer's basic details
      operationId: createProfile
      security:
        - MyUserPool: []
      tags:
        - profile
      requestBody:
        description: details entered by the customer
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    get:
      summary: creates customer profile with customer's basic details
      operationId: fetchProfile
      security:
        - MyUserPool: []
      tags:
        - profile
      responses:
        '302':
          description: Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDto'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /v1/customer/profile/{profileType}:
    put:
      summary: creates customer profile with customer's basic details
      operationId: updateProfile
      security:
        - MyUserPool: []
      tags:
        - profile
      requestBody:
        description: details entered by the customer
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      parameters:
        - in: path
          name: profileType
          schema:
            type: string
            enum: [INVOICE, ASSET, PURCHASE_ORDER]
          required: true
      responses:
        '302':
          description: Found
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  securitySchemes:
    MyUserPool:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
        - arn:aws:cognito-idp:us-east-1:706259184350:userpool/us-east-1_dd6taeJ12
  schemas:
    ErrorMessage:
      type: object
      required:
        - id
        - errorCode
        - message
      properties:
        id:
          type: string
          format: uuid
        errorCode:
          type: string
          example: '404.001.001'
        message:
          type: string
          example: 'GST Not Found'
        params:
          type: object
      title: ErrorMessage
    UserInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: ABC pvt. ltd.
        gstin:
          type: string
          example: '05ABNTY3290P8ZA'
        pan:
          type: string
          example: 'CPAA1234A'
        turnover:
          type: number
        udyogAadhaar:
          type: string
      title: UserInput
    Customer:
      type: object
      required:
        - userId
        - name
        - email
      properties:
        customerId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        name:
          type: string
          example: 'ABC pvt ltd'
        gstin:
          type: string
          example: '05ABNTY3290P8ZA'
        pan:
          type: string
          example: 'CPAA1234A'
        turnover:
          type: number
        udyogAadhaar:
          type: string
        email:
          type: string
        mobile:
          type: string
      title: Customer
    CustomerDto:
      type: object
      properties:
        name:
          type: string
          example: 'ABC pvt ltd'
        gstin:
          type: string
          example: '05ABNTY3290P8ZA'
        pan:
          type: string
          example: 'CPAA1234A'
        turnover:
          type: number
        udyogAadhaar:
          type: string
        email:
          type: string
        mobile:
          type: string
          example: 9988777444
        gstDetails:
          type: string
          format: json
          example: '{
                      "stjCd": "AP003",
                      "lgnm": "MS CORPORATION",
                      "stj": "BCP KODIKONDA",
                      "dty": "Regular",
                      "cxdt": "",
                      "gstin": "05ABNTY3290P8ZA",
                      "nba": [
                        "Bonded Warehouse",
                        "EOU / STP / EHTP",
                        "Factory / Manufacturing",
                        "Input Service Distributor (ISD)",
                        "Leasing Business"
                      ],
                      "lstupdt": "05/01/2017",
                      "rgdt": "05/05/2017",
                      "ctb": "Foreign LLP",
                      "sts": "Provisional",
                      "ctjCd": "AP004",
                      "ctj": "BCP THUMMAKUNTA",
                      "tradeNam": "ALTON PLASTIC PRIVATE LTD",
                      "adadr": [
                        {
                          "addr": {
                            "bnm": "ELPHINSTONE BUILDING",
                            "st": "10, VEER NARIMAN ROAD",
                            "loc": "FORT",
                            "bno": "10",
                            "stcd": "Rajasthan",
                            "flno": "1ST FLOOR",
                            "lt": "74.2179",
                            "lg": "27.0238",
                            "pncd": "400001"
                          },
                          "ntr": [
                            "Wholesale Business"
                          ]
                        }
                      ],
                      "pradr": {
                        "addr": {
                          "bnm": "KATGARA HOUSE",
                          "st": "15, L JAGMOHANDAS MARG",
                          "loc": "MALABAR HILL",
                          "bno": "5",
                          "stcd": "Maharashtra",
                          "flno": "4TH FLOOR",
                          "lt": "74.2179",
                          "lg": "27.0238",
                          "pncd": "400006"
                        },
                        "ntr": [
                          "Wholesale Business"
                        ]
                      }
                    }'
    GstProfile:
      type: object
      required:
        - userId
        - gstDetails
      properties:
        profileId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        profileType:
          type: string
          enum: [INVOICE, ASSET, PURCHASE_ORDER]
        gstDetails:
          type: string
          format: json
          example: '{
                      "stjCd": "AP003",
                      "lgnm": "MS CORPORATION",
                      "stj": "BCP KODIKONDA",
                      "dty": "Regular",
                      "cxdt": "",
                      "gstin": "05ABNTY3290P8ZA",
                      "nba": [
                        "Bonded Warehouse",
                        "EOU / STP / EHTP",
                        "Factory / Manufacturing",
                        "Input Service Distributor (ISD)",
                        "Leasing Business"
                      ],
                      "lstupdt": "05/01/2017",
                      "rgdt": "05/05/2017",
                      "ctb": "Foreign LLP",
                      "sts": "Provisional",
                      "ctjCd": "AP004",
                      "ctj": "BCP THUMMAKUNTA",
                      "tradeNam": "ALTON PLASTIC PRIVATE LTD",
                      "adadr": [
                        {
                          "addr": {
                            "bnm": "ELPHINSTONE BUILDING",
                            "st": "10, VEER NARIMAN ROAD",
                            "loc": "FORT",
                            "bno": "10",
                            "stcd": "Rajasthan",
                            "flno": "1ST FLOOR",
                            "lt": "74.2179",
                            "lg": "27.0238",
                            "pncd": "400001"
                          },
                          "ntr": [
                            "Wholesale Business"
                          ]
                        }
                      ],
                      "pradr": {
                        "addr": {
                          "bnm": "KATGARA HOUSE",
                          "st": "15, L JAGMOHANDAS MARG",
                          "loc": "MALABAR HILL",
                          "bno": "5",
                          "stcd": "Maharashtra",
                          "flno": "4TH FLOOR",
                          "lt": "74.2179",
                          "lg": "27.0238",
                          "pncd": "400006"
                        },
                        "ntr": [
                          "Wholesale Business"
                        ]
                      }
                    }'