spring:
  application:
    name: customer-profile-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ezyreach
    username: postgres
    password: aaa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baselineOnMigrate: true
    user: postgres
    password: aaa
    schemas: onboard
    locations: classpath:db/migration

server:
  port: 9290

logging:
  level:
    root: INFO
    com.ezreach: INFO

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
      exposure:
        include: ["health", "info", "prometheus", "loggers", "flyway", "conditions", "configprops"]
  info:
    git:
      mode: full

gst:
  baseUrl: "http://localhost:8093/gst/taxpayer"